# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=40)),
                ('Allocations1', models.IntegerField(help_text='Level 1 Castles', max_length=100)),
                ('Allocations2', models.IntegerField(help_text='Level 2 Castles', max_length=100)),
                ('Allocations3', models.IntegerField(help_text='Level 3 Castles', max_length=100)),
                ('Allocations4', models.IntegerField(help_text='Level 4 Castles', max_length=100)),
                ('Allocations5', models.IntegerField(help_text='Level 5 Castles', max_length=100)),
                ('Allocations6', models.IntegerField(help_text='Level 6 Castles', max_length=100)),
                ('Allocations7', models.IntegerField(help_text='Level 7 Castles', max_length=100)),
                ('Allocations8', models.IntegerField(help_text='Level 8 Castles', max_length=100)),
                ('Allocations9', models.IntegerField(help_text='Level 9 Castles', max_length=100)),
                ('Allocations10', models.IntegerField(help_text='Level 10 Castles', max_length=100)),
            ],
        ),
    ]
