# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Allocations1',
            field=models.IntegerField(help_text='Level 1 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations10',
            field=models.IntegerField(help_text='Level 10 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations2',
            field=models.IntegerField(help_text='Level 2 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations3',
            field=models.IntegerField(help_text='Level 3 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations4',
            field=models.IntegerField(help_text='Level 4 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations5',
            field=models.IntegerField(help_text='Level 5 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations6',
            field=models.IntegerField(help_text='Level 6 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations7',
            field=models.IntegerField(help_text='Level 7 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations8',
            field=models.IntegerField(help_text='Level 8 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='Allocations9',
            field=models.IntegerField(help_text='Level 9 Castles', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
