# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170601_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
