# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170602_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('script', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(help_text='Enter a name', max_length=40, unique=True),
        ),
    ]
