# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170602_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AddField(
            model_name='players',
            name='ties',
            field=models.IntegerField(default=0),
        ),
    ]
